# Site Settings
title: LOOP! Sophia Marinova
description: Welcome to my site. Still under construction!
url: ""
email: sophiajmarinova@gmail.com
github_username: sophiajm

# My Content
name: Sophia Marinova
profilepic: instagram-avatar.jpg
profileabout: > 
 Hello! I like math, data, and learning more about the world.
 This site is still under construction.

# Settings
markdown: kramdown
plugins:
 - jekyll-sitemap

# Contact Links
contactgithub: sophiajm
contactlinkedin: sophia-marinova
contactemail: sophiajmarinova@gmail.com

# Menubar Links
primarylinks:
  - title: Resume
    url: https://sophiajm.github.io/resume/
  - title: Portfolio
    url: https://sophiajm.github.io/portfolio/
    
# Buzzwords? Skills?
skills: 
  - Hello
  - Welcome
  - Goodbye
  
# Experience
roles:
  - title: 
    employer: 
    role: 
    start: 
    end: 
    description: 
  - title: 
    employer: 
    role: 
    start: 
    end: 
    description: 
  - title: 
    employer: 
    role: 
    start: 
    end: 
    description: 

# Education
education:
  - level: Bachelor of Science (B.S.)
    school: Georgia Institute of Technology
    completed: 2018
    major: Industrial & Systems Engineering
    concentrations: Operations Research, Materials Science

# Certifications
certification:
  - title: 
    received: 
    end: 
    software: 
  - title: 
    received: 
    end: 
    software: 
  - title: 
    received: 
    end: 
    software: 
  
# Current/interesting projects?
github:
- sophiajm/resume/
    
# stackoverflow?
stackoverflow:
  profileurl: https://stackoverflow.com/users/13931416/sophiajm?tab=profile
  #flairimageurl: http://stackoverflow.com/users/flair/258813.png

# optional additional info
#additionalinfo:
      




# With thanks to Rob Hinds, https://dzone.com/articles/how-to-turn-your-github-page-into-a-personalized-r
