theme: jekyll-theme-minimal
{% include profilepic.md %}
title: Welcome to Sophia's page!
description: I am using this site to keep track of completed and in-progress projects. email me to learn more.
