theme: jekyll-theme-minimal
image: ![profile pic](https://github.com/sophiajm3/sophiajm3.github.io/blob/master/images/IMG_2060%20-%20Copy.JPG)
title: Welcome to Sophia's page!
description: I am using this site to keep track of completed and in-progress projects. email me to learn more.
