theme: jekyll-theme-minimal
{% include IMG_2060 - Copy.JPG %}
title: Welcome to Sophia's page!
description: I am using this site to keep track of completed and in-progress projects. email me to learn more.
